from routers.authentication import authentication_router
from routers.department import department_router
from routers.class_router import class_router
from routers.subclass import subclass_router
from routers.supersubclass import supersubclass_router
from routers.order import order_router
from routers.suborder import suborder_router
from routers.family import family_router
from routers.genus import genus_router
from routers.plant import plant_router
from routers.areal import areal_router
from routers.morphology import morphology_router
from routers.ecology import ecology_router
from routers.note import note_router
from routers.apply import apply_router
from routers.addition import addition_router
from routers.map import map_router
from routers.image import image_router
from routers.search import search_router